on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Docker (Exact Deployment Steps)
      run: |
          docker-compose down
          git pull
          pwd
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Deploy Using Docker
        run: |
          echo "Deploy entered"
          docker-compose up -d --build
